/**
 * This file is generated by the ezpb CLI. Do not manually edit.
 * @internal
 */
/* eslint-disable */

import { ProtoGenAPI as __ProtoGenAPI } from '@wlabs/ezpb';

// Type error here? It means you need to re-generate this file with the same
// version of the ezpb client you're using.
const ApiVersionAssertion: __ProtoGenAPI.ProtoGenAPIVersion = 1;

export namespace hello_world {
  export interface Hello<TNum = number | Long> {
    body?: string;
  }

  export interface Hello_WithDefaultValues {
    body: string;
  }

  export namespace Hello {
    export const fullName = 'hello_world.Hello';

    export function verify(obj: Hello): string | null {
      return __ProtoGenAPI.injected.verify(fullName, obj);
    }

    export function encode(obj: Hello, delimitated = false): Uint8Array {
      return __ProtoGenAPI.injected.encode(fullName, obj, delimitated);
    }

    export function decode(
      data: Uint8Array,
      delimitated = false,
    ): Hello_WithDefaultValues {
      return __ProtoGenAPI.injected.decode(fullName, data, delimitated);
    }
  }

  export interface HelloServiceClient {
    hello: (
      req: hello_world.Hello,
    ) => Promise<hello_world.Hello_WithDefaultValues>;
  }

  export interface HelloServiceHandler {
    hello: (
      req: hello_world.Hello_WithDefaultValues,
      ctx: __ProtoGenAPI.CallContext,
    ) => Promise<hello_world.Hello> | hello_world.Hello;
  }

  export namespace HelloService {
    export const fullName = 'hello_world.HelloService';

    export function registerHandler(
      scope: __ProtoGenAPI.ServiceScope,
      handler: Partial<HelloServiceHandler>,
    ): () => void {
      return __ProtoGenAPI.injected.registerHandler(fullName, scope, handler);
    }

    export function createClient(Node: __ProtoGenAPI.Node): HelloServiceClient {
      return __ProtoGenAPI.injected.createClient(fullName, Node);
    }
  }
}

// This registers the reflection object for runtime use. It's a binary
// (base64 encoded) `protobuf wlabs.ezpb.meta.Meta` message.
__ProtoGenAPI.addMetaDefinitionBase64(
  'ClAKGwoLaGVsbG9fd29ybGQSDEhlbGxvU2VydmljZRIxCgVIZWxsbxIRaGVsbG9fd29ybGQuSGVsbG8aEWhlbGxvX3dvcmxkLkhlbGxvIAAoABIuChQKC2hlbGxvX3dvcmxkEgVIZWxsbxIWCgRib2R5EAEaBnN0cmluZyABKAA4Ag==',
);
